spring.application.name=idat-proyecto-final
server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6brkvh5pdvs73efoq70-a.oregon-postgres.render.com:5432/db_gestion_tareas
spring.datasource.username=posgrest
spring.datasource.password=4UjtmGRBDvJlQFrWTZagyakFM1lHfpMx
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Configure circular reference handling
spring.main.allow-circular-references=true

# JWT Configuration
jwt.secret=mi-clave-super-secreta-proyecto-final-123456789-idat-2024-seguridad-maxima
jwt.expiration=3000000
